version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=midwestten
      - MYSQL_USER=local
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 81:3306
      
  app:
    image: midwestten:latest 
    ports:
       - 80:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/midwestten?autoReconnect=true&useSSL=false
    depends_on:
       - db